--게시판 컬럼 수정
ALTER TABLE TM_BBS ADD (EMAIL VARCHAR2(255));
ALTER TABLE TM_BBS MODIFY (save_fnm VARCHAR2(255));
ALTER TABLE TM_BBS MODIFY (real_fnm VARCHAR2(255));
COMMIT;

--공지사항(직영) 데이터이전
INSERT INTO TM_BBS (SEQ,TITL,CONT,CNT,SAVE_FNM,REAL_FNM,FILE_PATH,INDT,INPS,TYPECD,EMAIL)
 (SELECT NUMID,SUBJECT,CONTENT,READNO,DOWNFILE,DOWNFILE,'/uploadedfile/bbs/notice',TO_DATE(REPLACE(REPLACE(WRITEDATE,'AM','오전'),'PM','오후'),'MM DD YYYY HH:MIPM'),WRITER,2,EMAIL FROM TBL_IN_NOTICE);
COMMIT;

 --공지사항(전체) 데이터이전
DECLARE
	i_seq NUMBER := 0;
BEGIN
	DBMS_OUTPUT.ENABLE ;
  
  FOR tmp_list IN  (SELECT TITL,CONT,CNT,SAVE_FNM,REAL_FNM,'/uploadedfile/bbs/notice' as path,INDT,INPS,1 as typecd FROM TM_NOTICE ORDER BY SEQ) LOOP
    SELECT NVL(MAX(TO_NUMBER(SEQ)),0)+1 into i_seq FROM TM_BBS;
    
    INSERT INTO TM_BBS (SEQ,TITL,CONT,CNT,SAVE_FNM,REAL_FNM,FILE_PATH,INDT,INPS,TYPECD) 
    values (i_seq,tmp_list.TITL,tmp_list.CONT,tmp_list.CNT,tmp_list.SAVE_FNM,tmp_list.REAL_FNM,tmp_list.path,tmp_list.INDT,tmp_list.INPS,tmp_list.typecd);
  END LOOP;

	DBMS_OUTPUT.PUT_LINE('데이터 처리 완료');
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('(에러 발생)'||SQLERRM);
END;

--환불내역조회 일반,학생 구분코드
ALTER TABLE TBL_EA_REFUND_ALL ADD (TYPECD VARCHAR2(3));
COMMENT ON COLUMN TBL_EA_REFUND_ALL.TYPECD IS '일반학생구분(일반1,학생2)';
UPDATE TBL_EA_REFUND_ALL SET TYPECD='1' where gubun='일반';
UPDATE TBL_EA_REFUND_ALL SET TYPECD='2' where gubun='학생';
COMMIT;



--통계테이블생성

  CREATE TABLE TM_STAT_PERUSE
   (	
   	YYMM VARCHAR2(6 BYTE) NOT NULL, 
	BOSEQ VARCHAR2(6 BYTE) NOT NULL, 
	NEWSCD VARCHAR2(3 BYTE) NOT NULL, 
	GNO VARCHAR2(3 BYTE) NOT NULL, 
	READTYPECD011 VARCHAR2(10 BYTE) DEFAULT 0, 
	READTYPECD012 VARCHAR2(10 BYTE) DEFAULT 0, 
	READTYPECD013 VARCHAR2(10 BYTE) DEFAULT 0, 
	READTYPECD014 VARCHAR2(10 BYTE) DEFAULT 0, 
	READTYPECD015 VARCHAR2(10 BYTE) DEFAULT 0, 
	READTYPECD021 VARCHAR2(10 BYTE) DEFAULT 0, 
	READTYPECD022 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_QTY1 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_QTY2 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_QTY3 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_QTY4 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_QTY5 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_QTY6 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_QTY7 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_ETC_LOSS VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_ETC_FINANCE VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_ETC_LEAVE VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_LIST_PRICE VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_MISU_AMT VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_ALL_MISU_AMT VARCHAR2(10 BYTE) DEFAULT 0, 
	MONTH_SUGUM VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_YUGA_SINSU VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_YUGA_MISU VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_ETC1 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_DEPOSIT VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_SGBBCD011 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_SGBBCD012 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_SGBBCD013 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_SGBBCD021 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_SGBBCD022 VARCHAR2(10 BYTE) DEFAULT 0, 
	SUM_ETC2 VARCHAR2(10 BYTE) DEFAULT 0,
	SUM_MISU VARCHAR2(10 BYTE) DEFAULT 0,
	MON_SUM_ETC1 VARCHAR2(10 BYTE) DEFAULT 0,
	MON_SUM_MISU VARCHAR2(10 BYTE) DEFAULT 0,
	MON_SUM_SGBBCD011 VARCHAR2(10 BYTE) DEFAULT 0,
	MON_SUM_SGBBCD012 VARCHAR2(10 BYTE) DEFAULT 0,
	MON_SUM_SGBBCD013 VARCHAR2(10 BYTE) DEFAULT 0,
	MON_SUM_SGBBCD021 VARCHAR2(10 BYTE) DEFAULT 0,
	MON_SUM_SGBBCD022 VARCHAR2(10 BYTE) DEFAULT 0,
	MON_SUM_ETC2 VARCHAR2(10 BYTE) DEFAULT 0,
	
	
	CONSTRAINT TM_STAT_PERUSE_PK PRIMARY KEY (YYMM, BOSEQ, NEWSCD, GNO));
   

   
COMMENT ON TABLE TM_STAT_PERUSE IS '통계';
COMMENT ON COLUMN TM_STAT_PERUSE.YYMM IS '구독년월';
COMMENT ON COLUMN TM_STAT_PERUSE.BOSEQ IS '지국코드';
COMMENT ON COLUMN TM_STAT_PERUSE.NEWSCD IS '뉴스코드';
COMMENT ON COLUMN TM_STAT_PERUSE.GNO IS '구역';
COMMENT ON COLUMN TM_STAT_PERUSE.READTYPECD011 IS '일반';
COMMENT ON COLUMN TM_STAT_PERUSE.READTYPECD012 IS '학생(지국)';
COMMENT ON COLUMN TM_STAT_PERUSE.READTYPECD013 IS '학생(본사)';
COMMENT ON COLUMN TM_STAT_PERUSE.READTYPECD014 IS '병독';
COMMENT ON COLUMN TM_STAT_PERUSE.READTYPECD015 IS '교육';
COMMENT ON COLUMN TM_STAT_PERUSE.READTYPECD021 IS '기증';
COMMENT ON COLUMN TM_STAT_PERUSE.READTYPECD022 IS '홍보';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_QTY1 IS '준유가(1개월)';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_QTY2 IS '준유가(2개월)';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_QTY3 IS '준유가(3개월)';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_QTY4 IS '준유가(4개월)';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_QTY5 IS '준유가(5개월)';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_QTY6 IS '준유가(6개월)';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_QTY7 IS '준유가(기타)';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_ETC_LOSS IS '결손부수';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_ETC_FINANCE IS '재무부수';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_ETC_LEAVE IS '휴독부수';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_LIST_PRICE IS '일반독자중 구독료가 정가인 독자';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_MISU_AMT IS '전월미수';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_ALL_MISU_AMT IS '총전월미수';
COMMENT ON COLUMN TM_STAT_PERUSE.MONTH_SUGUM IS '당월수금예정액';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_YUGA_SINSU IS '유가조정액신수';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_YUGA_MISU IS '유가조정액미수';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_ETC1 IS '재무,결손,휴독 금액';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_DEPOSIT IS '선입금';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_SGBBCD011 IS '지로';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_SGBBCD012 IS '방문';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_SGBBCD013 IS '통장입금';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_SGBBCD021 IS '자동이체';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_SGBBCD022 IS '카드';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_ETC2 IS '기타';
COMMENT ON COLUMN TM_STAT_PERUSE.SUM_MISU IS '미수총계';
COMMENT ON COLUMN TM_STAT_PERUSE.MON_SUM_ETC1 IS '당월 재무,결손,휴독 금액';
COMMENT ON COLUMN TM_STAT_PERUSE.MON_SUM_MISU IS '당월미수총계';
COMMENT ON COLUMN TM_STAT_PERUSE.MON_SUM_SGBBCD011 IS '당월지로';
COMMENT ON COLUMN TM_STAT_PERUSE.MON_SUM_SGBBCD012 IS '당월방문';
COMMENT ON COLUMN TM_STAT_PERUSE.MON_SUM_SGBBCD013 IS '당월통장입금';
COMMENT ON COLUMN TM_STAT_PERUSE.MON_SUM_SGBBCD021 IS '당월자동이체';
COMMENT ON COLUMN TM_STAT_PERUSE.MON_SUM_SGBBCD022 IS '당월카드';
COMMENT ON COLUMN TM_STAT_PERUSE.MON_SUM_ETC2 IS '당월기타';
COMMIT;


ALTER TABLE TM_STAT_PERUSE ADD READTYPECD016 VARCHAR2(10 BYTE) DEFAULT 0;
COMMENT ON COLUMN TM_STAT_PERUSE.READTYPECD016 IS '본사직원';
COMMIT;
