-- DROP TABLE FILE_T;

-- 업로드 파일명 저장 테이블 생성 (실서버에는 있음)
--CREATE TABLE FILE_T (
--	NUMID		NUMBER(19)			NOT NULL,
--	FILENAME	NVARCHAR2(50)		NULL,
--	I_DATE		DATE				NULL,
--	LOSS		NVARCHAR2(50)		NULL,
--	CONSTRAINT PK_EDI_OVER PRIMARY KEY(NUMID)
--  );
--
--COMMENT ON TABLE FILE_T IS '업로드된 파일명정보';
--COMMENT ON COLUMN FILE_T.NUMID IS '순차번호';
--COMMENT ON COLUMN FILE_T.FILENAME IS '파일명';
--COMMENT ON COLUMN FILE_T.I_DATE IS '날짜';
--COMMENT ON COLUMN FILE_T.LOSS IS '';
--COMMIT;

-- 과입금 테이블 생성
CREATE TABLE EDI_OVER (
	NUMID		NUMBER(19)			NOT NULL,
	EDINUMID	NUMBER(19)			NULL,
	OVERMONEY	NUMBER				NULL,
	REGDATE		DATE				NULL,
	CONSTRAINT PK_EDI_OVER PRIMARY KEY(NUMID)
  );

COMMENT ON TABLE EDI_OVER IS '과입금정보';
COMMENT ON COLUMN EDI_OVER.NUMID IS '순차번호';
COMMENT ON COLUMN EDI_OVER.EDINUMID IS 'EDI번호';
COMMENT ON COLUMN EDI_OVER.OVERMONEY IS '과입금액';
COMMENT ON COLUMN EDI_OVER.REGDATE IS '등록일';
COMMIT;


-- 월마감 내역 테이블 생성
CREATE TABLE TM_MONTHCLOSE_HIST (
	SEQ			NUMBER				NOT NULL,
	SGYYMM		VARCHAR2(6)			NOT NULL,
	SDATE		VARCHAR2(8)			NULL,
	EDATE		VARCHAR2(8)			NULL,
	REGDATE		DATE				NULL,
    REGUSER		VARCHAR2(50)		NULL,
	CONSTRAINT PK_TM_MONTHCLOSE_HIST PRIMARY KEY(SEQ)
  );

COMMENT ON TABLE TM_MONTHCLOSE_HIST IS '월마감 내역';
COMMENT ON COLUMN TM_MONTHCLOSE_HIST.SEQ IS '순차번호';
COMMENT ON COLUMN TM_MONTHCLOSE_HIST.SGYYMM IS '수금년월(YYYYMM)';
COMMENT ON COLUMN TM_MONTHCLOSE_HIST.SDATE IS '시작일(YYYYMMDD)';
COMMENT ON COLUMN TM_MONTHCLOSE_HIST.EDATE IS '종료일(YYYYMMDD)';
COMMENT ON COLUMN TM_MONTHCLOSE_HIST.REGDATE IS '등록일';
COMMENT ON COLUMN TM_MONTHCLOSE_HIST.REGUSER IS '등록자ID';
COMMIT;
