--독자 이전 테이블 이전 부수 인수부수 생성
ALTER TABLE TM_READER_MOVE ADD (BO_QTY VARCHAR2(4));
ALTER TABLE TM_READER_MOVE ADD (AO_QTY VARCHAR2(4));

COMMENT ON COLUMN MKDEV.TM_READER_MOVE.AO_QTY IS '인수부수';
COMMENT ON COLUMN MKDEV.TM_READER_MOVE.BO_QTY IS '이전부수';

UPDATE TM_READER_MOVE SET BO_QTY='1' , AO_QTY='1';

ALTER TABLE TM_READER_MOVE MODIFY (AO_QTY VARCHAR2(4) NOT NULL );
ALTER TABLE TM_READER_MOVE MODIFY (BO_QTY VARCHAR2(4) NOT NULL );

--수금이력 테이블 SEQ 수정
ALTER TABLE Th_READER_SUGM MODIFY (SEQ VARCHAR2(4));

--SUPERADMIN 생성
INSERT INTO TMP_USER
(ID , COMPCD , NAME , PWD , USEYN , INDT )
VALUES
('SUPERADMIN' , 'A' , 'SUPERADMIN' , 'ADMIN2011' , 'Y' , SYSDATE);

--자동이체 통화기록 테이블
CREATE TABLE TBL_CALL_LOG (
	NUMID VARCHAR2(19) NOT NULL,
	CALLSEQ VARCHAR2(4) NOT NULL,
	TYPECD VARCHAR2(1) NOT NULL,
	INDATE DATE NOT NULL,
	REMK VARCHAR2(300) );
                       
ALTER TABLE TBL_CALL_LOG ADD CONSTRAINT TBL_CALL_LOG PRIMARY KEY (NUMID, CALLSEQ);

COMMENT ON TABLE MKDEV.TBL_CALL_LOG IS '자동이체통화내역';
COMMENT ON COLUMN MKDEV.TBL_CALL_LOG.NUMID IS '자동이체일련번호';
COMMENT ON COLUMN MKDEV.TBL_CALL_LOG.CALLSEQ IS '통화기록일련번호';
COMMENT ON COLUMN MKDEV.TBL_CALL_LOG.TYPECD IS '1:일반 2:학생';
COMMENT ON COLUMN MKDEV.TBL_CALL_LOG.INDATE IS '생성일';
COMMENT ON COLUMN MKDEV.TBL_CALL_LOG.REMK IS '통화내역';	


--독자관리 통화로그
CREATE TABLE TM_CALL_LOG (
	READNO VARCHAR2(9) NOT NULL,
	NEWSCD VARCHAR2(3) NOT NULL,
	SEQ VARCHAR2(4) NOT NULL,
	CALLSEQ VARCHAR2(4) NOT NULL,
	INDATE DATE NOT NULL,
	REMK VARCHAR2(300) );
                       
ALTER TABLE TM_CALL_LOG ADD CONSTRAINT TM_CALL_LOG_PK PRIMARY KEY (READNO, NEWSCD, SEQ , CALLSEQ);

COMMENT ON TABLE MKDEV.TM_CALL_LOG IS '통화내역';
COMMENT ON COLUMN MKDEV.TM_CALL_LOG.READNO IS '독자번호';
COMMENT ON COLUMN MKDEV.TM_CALL_LOG.NEWSCD IS '신문코드';
COMMENT ON COLUMN MKDEV.TM_CALL_LOG.SEQ IS '일련번호';
COMMENT ON COLUMN MKDEV.TM_CALL_LOG.CALLSEQ IS '통화기록일련번호';
COMMENT ON COLUMN MKDEV.TM_CALL_LOG.INDATE IS '생성일';
COMMENT ON COLUMN MKDEV.TM_CALL_LOG.REMK IS '통화내역';

COMMIT;




