--CREATE INDEX IDX_TBL_USERS_1   ON  TBL_USERS (NUMID ) ;
CREATE INDEX IDX_TBL_USERS_2   ON  TBL_USERS (READNO ) ;
CREATE INDEX IDX_TBL_USERS_3   ON  TBL_USERS (USERNAME ) ;
CREATE INDEX IDX_TBL_USERS_4   ON  TBL_USERS (BANK_NUM ) ;
CREATE INDEX IDX_TBL_USERS_5   ON  TBL_USERS (BANK_NAME ) ;
--CREATE INDEX IDX_TBL_USERS_STU_1   ON  TBL_USERS_STU (NUMID ) ;
CREATE INDEX IDX_TBL_USERS_STU_2   ON  TBL_USERS_STU (READNO ) ;
CREATE INDEX IDX_TBL_USERS_STU_3   ON  TBL_USERS_STU (USERNAME ) ;
CREATE INDEX IDX_TBL_USERS_STU_4   ON  TBL_USERS_STU (REALJIKUK ) ;
CREATE INDEX IDX_TBL_USERS_STU_5   ON  TBL_USERS_STU (BANK_NUM ) ;
CREATE INDEX IDX_TBL_USERS_STU_6   ON  TBL_USERS_STU (BANK_NAME ) ;
CREATE INDEX IDX_TBL_USERS_STU_7   ON  TBL_USERS_STU (JIKUK,SERIAL ) ;
CREATE INDEX IDX_TBL_USERS_STU_8   ON  TBL_USERS_STU (SAUP ) ;
CREATE INDEX IDX_TBL_USERS_STU_9   ON  TBL_USERS_STU (STU_SCH ) ;
CREATE INDEX IDX_TBL_USERS_STU_10   ON  TBL_USERS_STU (STU_PROF ) ;
COMMIT;

CREATE INDEX IDX_TBL_EA_LOG_1   ON  TBL_EA_LOG (NUMID ) ;
CREATE INDEX IDX_TBL_EA_LOG_2   ON  TBL_EA_LOG (FILENAME, CMSDATE ) ;
CREATE INDEX IDX_TBL_EA_LOG_3   ON  TBL_EA_LOG (CMSTYPE, CMSRESULT ) ;

CREATE INDEX IDX_TBL_EA21_LOG_1   ON  TBL_EA21_LOG (NUMID ) ;
COMMIT;

CREATE INDEX IDX_TBL_EA_LOG_STU_1   ON  TBL_EA_LOG_STU (NUMID ) ;
CREATE INDEX IDX_TBL_EA_LOG_STU_2   ON  TBL_EA_LOG_STU (FILENAME, CMSDATE ) ;
CREATE INDEX IDX_TBL_EA_LOG_STU_3   ON  TBL_EA_LOG_STU (CMSTYPE, CMSRESULT ) ;
COMMIT;

CREATE INDEX IDX_TBL_CMSDATA_1   ON  TBL_CMSDATA (LOGDATE ) ;
COMMIT;

CREATE INDEX IDX_EDI_1	ON EDI (E_ERROR, E_EDATE);
CREATE INDEX IDX_EDI_2	ON EDI (E_ERROR, E_EDATE, E_JCODE);
COMMIT;

CREATE INDEX IDX_TM_AGENCY_1   ON  TM_AGENCY (USERID ) ;
COMMIT;

--CREATE INDEX IDX_TM_READER_NEWS_1 	ON TM_READER_NEWS (SGTYPE);
CREATE INDEX IDX_TM_READER_NEWS_4 	ON TM_READER_NEWS (BOSEQ,GNO,READTYPECD,NEWSCD,STDT);
--CREATE INDEX IDX_TM_READER_NEWS_5 	ON TM_READER_NEWS (NEWSCD,READNO,SEQ,BNO);
COMMIT;

--CREATE INDEX TM_READER_SUGM_1 	ON TM_READER_SUGM (SGBBCD, READNO);
CREATE INDEX TM_READER_SUGM_2 	ON TM_READER_SUGM (SGBBCD, NEWSCD, READNO);
CREATE INDEX TM_READER_SUGM_3 	ON TM_READER_SUGM (BOSEQ, NEWSCD, CLDT, SGBBCD);
COMMIT;

CREATE INDEX IDX_TC_COMMON_1 	ON TC_COMMON (USEYN, CDCLSF);
COMMIT;

CREATE INDEX IDX_FILE_T_1   ON  FILE_T (FILENAME ) ;
COMMIT;

CREATE INDEX IDX_EDI_OVER_1   ON  EDI_OVER (EDINUMID ) ;
COMMIT;

