  CREATE TABLE MKDEV.TBL_USERS_TMP (
    NUMID           NUMBER(19)         NOT NULL,
    JIKUK           CHAR(6)                NULL,
    SERIAL          CHAR(5)                NULL,
    INTYPE          NVARCHAR2(10)          NULL,
    USERNAME        NVARCHAR2(40)          NULL,
    USERID          NVARCHAR2(12)          NULL,
    PASSWD          NVARCHAR2(12)          NULL,
    JUMIN1          CHAR(6)                NULL,
    JUMIN2          CHAR(7)                NULL,
    SAUP            VARCHAR2(13)           NULL,
    GUBUN           NVARCHAR2(10)          NULL,
    EMAIL           NVARCHAR2(150)         NULL,
    ZIP1            CHAR(3)                NULL,
    ZIP2            CHAR(3)                NULL,
    ADDR1           NVARCHAR2(150)         NULL,
    ADDR2           NVARCHAR2(150)         NULL,
    PHONE           VARCHAR2(15)           NULL,
    HANDY           VARCHAR2(15)           NULL,
    BIRTHD          DATE                   NULL,
    SL              CHAR(1)                NULL,
    LEVELS          CHAR(1)                NULL,
    DIFF            CHAR(1)                NULL,
    INDATE          DATE                   NULL,
    LASTDATE        DATE                   NULL,
    COUNTERS        NUMBER(10)             NULL,
    LOGS            CLOB                   NULL,
    MEMO            CLOB                   NULL,
    SDATE           DATE                   NULL,
    WHOSTEP         CHAR(1)                NULL,
    RDATE           DATE                   NULL,
    RDATE_RESULT    NVARCHAR2(50)          NULL,
    BANK            CHAR(7)                NULL,
    BANK_NUM        CHAR(16)               NULL,
    BANK_NAME       NVARCHAR2(50)          NULL,
    REL             NVARCHAR2(50)          NULL,
    BANK_MONEY      NVARCHAR2(13)          NULL,
    BUSU            NVARCHAR2(10)          NULL,
    R_OUT_DATE      DATE                   NULL,
    R_OUT_RESULT    NVARCHAR2(50)          NULL,
    STATUS          NVARCHAR2(50)          NULL,
    TRASHS          CLOB                   NULL,
    READNO          NVARCHAR2(9)           NULL
  );


  CREATE TABLE MKDEV.TBL_USERS_STU_TMP (
    NUMID           NUMBER(19)         NOT NULL,
    JIKUK           CHAR(6)                NULL,
    SERIAL          CHAR(5)                NULL,
    INTYPE          NVARCHAR2(10)          NULL,
    USERNAME        NVARCHAR2(40)          NULL,
    USERID          NVARCHAR2(12)          NULL,
    PASSWD          NVARCHAR2(12)          NULL,
    JUMIN1          CHAR(6)                NULL,
    JUMIN2          CHAR(7)                NULL,
    SAUP            VARCHAR2(13)           NULL,
    GUBUN           NVARCHAR2(10)          NULL,
    EMAIL           NVARCHAR2(150)         NULL,
    ZIP1            CHAR(3)                NULL,
    ZIP2            CHAR(3)                NULL,
    ADDR1           NVARCHAR2(150)         NULL,
    ADDR2           NVARCHAR2(150)         NULL,
    PHONE           VARCHAR2(15)           NULL,
    HANDY           VARCHAR2(15)           NULL,
    BIRTHD          DATE                   NULL,
    SL              CHAR(1)                NULL,
    LEVELS          CHAR(1)                NULL,
    DIFF            CHAR(1)                NULL,
    INDATE          DATE                   NULL,
    LASTDATE        DATE                   NULL,
    COUNTERS        NUMBER(10)             NULL,
    LOGS            CLOB                   NULL,
    MEMO            CLOB                   NULL,
    SDATE           DATE                   NULL,
    WHOSTEP         CHAR(1)                NULL,
    RDATE           DATE                   NULL,
    RDATE_RESULT    NVARCHAR2(50)          NULL,
    BANK            CHAR(7)                NULL,
    BANK_NUM        CHAR(16)               NULL,
    BANK_NAME       NVARCHAR2(50)          NULL,
    REL             NVARCHAR2(50)          NULL,
    BANK_MONEY      NVARCHAR2(13)          NULL,
    BUSU            NVARCHAR2(10)          NULL,
    R_OUT_DATE      DATE           NULL,
    R_OUT_RESULT    NVARCHAR2(50)  NULL,
    STATUS          NVARCHAR2(50)  NULL,
    TRASHS          CLOB           NULL,
    STU_SCH         NVARCHAR2(50)  NULL,
    STU_PART        NVARCHAR2(50)  NULL,
    STU_CLASS       NVARCHAR2(2)   NULL,
    STU_PROF        NVARCHAR2(50)  NULL,
    STU_ADM         NVARCHAR2(50)  NULL,
    STU_CALLER      NVARCHAR2(50)  NULL,
    READNO          NVARCHAR2(9)   NULL
  );

    CREATE TABLE MKDEV.TM_READER_SUGM_TMP (
    READNO        VARCHAR2(9)      NOT NULL,
    NEWSCD        VARCHAR2(3)      NOT NULL,
    YYMM          VARCHAR2(6)      NOT NULL,
    SEQ           VARCHAR2(4)      NOT NULL,
    BOSEQ         VARCHAR2(6)          NULL,
    SGBBCD        VARCHAR2(3)          NULL,
    SGGBCD        VARCHAR2(3)          NULL,
    BILLAMT       NUMBER(8)            NULL,
    BILLQTY       NUMBER(5)            NULL,
    SGYYMM        VARCHAR2(6)          NULL,
    AMT           NUMBER(8)            NULL,
    LOSSAMT       NUMBER(8)            NULL,
    FEE1          NUMBER(6)            NULL,
    FEE2          NUMBER(6)            NULL,
    FEE3          NUMBER(6)            NULL,
    SNDT          VARCHAR2(8)          NULL,
    ICDT          VARCHAR2(8)          NULL,
    CLDT          VARCHAR2(8)          NULL,
    WRKNO         VARCHAR2(10)         NULL,
    EDIPROCNO     VARCHAR2(30)         NULL,
    AUTOPROCNO    VARCHAR2(30)         NULL,
    BILLTYPECD    VARCHAR2(3)          NULL,
    REMK          VARCHAR2(50)         NULL,
    INDT          DATE                 NULL,
    INPS          VARCHAR2(20)         NULL,
    CHGDT         DATE                 NULL,
    CHGPS         VARCHAR2(20)         NULL,
    CONSTRAINT PK_TM_READER_SUGM_TMP PRIMARY KEY(READNO,NEWSCD,YYMM,SEQ)
  );
  
  CREATE TABLE MKDEV.TM_READER_TMP (
    READNO        VARCHAR2(9)      NOT NULL,
    RDRGRAD       VARCHAR2(3)          NULL,
    PRN           VARCHAR2(13)         NULL,
    ERNNO         VARCHAR2(13)         NULL,
    EMAIL         VARCHAR2(30)         NULL,
    WEDDYN        CHAR(1)              NULL,
    WEDDANVYDT    VARCHAR2(8)          NULL,
    BIDT          VARCHAR2(8)          NULL,
    LUSOCLSFCD    VARCHAR2(3)          NULL,
    TASKCD        VARCHAR2(3)          NULL,
    INTFLDCD      VARCHAR2(3)          NULL,
    INDT          DATE                 NULL,
    INPS          VARCHAR2(20)         NULL,
    CHGDT         DATE                 NULL,
    CHGPS         VARCHAR2(20)         NULL,
    CONSTRAINT PK_TM_READER_TMP PRIMARY KEY(READNO)
  );
  
  CREATE TABLE MKDEV.TM_READER_NEWS_TMP (
    READNO        VARCHAR2(9)       NOT NULL,
    NEWSCD        VARCHAR2(3)       NOT NULL,
    SEQ           VARCHAR2(4)       NOT NULL,
    BOSEQ         VARCHAR2(6)           NULL,
    BOREADNO      VARCHAR2(5)           NULL,
    GNO           VARCHAR2(3)           NULL,
    BNO           VARCHAR2(3)           NULL,
    SNO           VARCHAR2(3)           NULL,
    READTYPECD    VARCHAR2(3)           NULL,
    READNM        VARCHAR2(50)          NULL,
    OFFINM        VARCHAR2(50)          NULL,
    HOMETEL1      VARCHAR2(4)           NULL,
    HOMETEL2      VARCHAR2(4)           NULL,
    HOMETEL3      VARCHAR2(4)           NULL,
    MOBILE1       VARCHAR2(4)           NULL,
    MOBILE2       VARCHAR2(4)           NULL,
    MOBILE3       VARCHAR2(4)           NULL,
    DLVZIP        VARCHAR2(7)           NULL,
    DLVADRS1      VARCHAR2(100)         NULL,
    DLVADRS2      VARCHAR2(100)         NULL,
    DLVSTRNM      VARCHAR2(30)          NULL,
    DLVSTRNO      VARCHAR2(10)          NULL,
    APTCD         VARCHAR2(3)           NULL,
    APTDONG       VARCHAR2(4)           NULL,
    APTHO         VARCHAR2(4)           NULL,
    SGTYPE        VARCHAR2(3)           NULL,
    SGINFO        VARCHAR2(50)          NULL,
    SGTEL1        VARCHAR2(4)           NULL,
    SGTEL2        VARCHAR2(4)           NULL,
    SGTEL3        VARCHAR2(4)           NULL,
    UPRICE        NUMBER(7)             NULL,
    QTY           NUMBER(4)             NULL,
    RSDTYPECD     VARCHAR2(3)           NULL,
    DLVTYPECD     VARCHAR2(3)           NULL,
    DLVPOSICD     VARCHAR2(3)           NULL,
    HJPATHCD      VARCHAR2(3)           NULL,
    HJTYPECD      VARCHAR2(3)           NULL,
    HJPSREGCD     VARCHAR2(7)           NULL,
    HJPSNM        VARCHAR2(50)          NULL,
    HJDT          VARCHAR2(8)           NULL,
    SGBGMM        VARCHAR2(6)           NULL,
    SGEDMM        VARCHAR2(6)           NULL,
    SGCYCLE       NUMBER(2)             NULL,
    STDT          VARCHAR2(8)           NULL,
    STSAYOU       VARCHAR2(3)           NULL,
    APLCDT        VARCHAR2(8)           NULL,
    APLCNO        VARCHAR2(5)           NULL,
    REMK          VARCHAR2(300)         NULL,
    INDT          DATE                  NULL,
    INPS          VARCHAR2(20)          NULL,
    CHGDT         DATE                  NULL,
    CHGPS         VARCHAR2(20)          NULL,
    SPGCD         VARCHAR2(3)           NULL,
    BNSBOOKCD     VARCHAR2(3)           NULL,
    CONSTRAINT PK_TM_READER_NEWS_TMP PRIMARY KEY(READNO,NEWSCD,SEQ)
  );
