-- tbl_users, tbl_users_stu 테이블에 bank 컬럼 수정
UPDATE TBL_USERS SET bank = TRIM(bank) || '0' WHERE LENGTH(TRIM(bank)) = 6;

UPDATE TBL_USERS_stu SET bank = TRIM(bank) || '0' WHERE LENGTH(TRIM(bank)) = 6;
COMMIT;

--UPDATE TBL_USERS SET bank = '0' || SUBSTR(bank,0,6) WHERE TRIM(bank) IN ('5300000','4500000','8100000','4900000','3200000','3100000','7100000');
--UPDATE TBL_USERS_stu SET bank = '0' || SUBSTR(bank,0,6) WHERE TRIM(bank) IN ('5300000','4500000','8100000','4900000','3200000','3100000','7100000');
--COMMIT;

-- EB11 파일 처리를 위해 SERIAL 컬럼을 VARCHAR(9)로 변경 
ALTER TABLE TBL_USERS ADD SERIALTMP VARCHAR2(9);
UPDATE TBL_USERS SET SERIALTMP = SERIAL;
ALTER TABLE TBL_USERS DROP COLUMN SERIAL;
ALTER TABLE TBL_USERS ADD SERIAL VARCHAR2(9);
UPDATE TBL_USERS SET SERIAL = SERIALTMP;
ALTER TABLE TBL_USERS DROP COLUMN SERIALTMP;
COMMIT;

ALTER TABLE TBL_USERS_STU ADD SERIALTMP VARCHAR2(9);
UPDATE TBL_USERS_STU SET SERIALTMP = SERIAL;
ALTER TABLE TBL_USERS_STU DROP COLUMN SERIAL;
ALTER TABLE TBL_USERS_STU ADD SERIAL VARCHAR2(9);
UPDATE TBL_USERS_STU SET SERIAL = SERIALTMP;
ALTER TABLE TBL_USERS_STU DROP COLUMN SERIALTMP;
COMMIT;


-- EB11 파일 처리를 위해 컬럼 길이 변경 CHAR(7) -> VARCHAR(8)로 변경 
ALTER TABLE TBL_CMSEA11DATA_LOG ADD TOTALS_TMP VARCHAR2(8);
UPDATE TBL_CMSEA11DATA_LOG SET TOTALS_TMP = '0' || TOTALS;
ALTER TABLE TBL_CMSEA11DATA_LOG DROP COLUMN TOTALS;
ALTER TABLE TBL_CMSEA11DATA_LOG ADD TOTALS VARCHAR2(8);
UPDATE TBL_CMSEA11DATA_LOG SET TOTALS = TOTALS_TMP;
ALTER TABLE TBL_CMSEA11DATA_LOG DROP COLUMN TOTALS_TMP;
COMMIT;

ALTER TABLE TBL_CMSEA11DATA_LOG ADD TYPE1_TMP VARCHAR2(8);
UPDATE TBL_CMSEA11DATA_LOG SET TYPE1_TMP = '0' || TYPE1;
ALTER TABLE TBL_CMSEA11DATA_LOG DROP COLUMN TYPE1;
ALTER TABLE TBL_CMSEA11DATA_LOG ADD TYPE1 VARCHAR2(8);
UPDATE TBL_CMSEA11DATA_LOG SET TYPE1 = TYPE1_TMP;
ALTER TABLE TBL_CMSEA11DATA_LOG DROP COLUMN TYPE1_TMP;
COMMIT;

ALTER TABLE TBL_CMSEA11DATA_LOG ADD TYPE2_TMP VARCHAR2(8);
UPDATE TBL_CMSEA11DATA_LOG SET TYPE2_TMP = '0' || TYPE2;
ALTER TABLE TBL_CMSEA11DATA_LOG DROP COLUMN TYPE2;
ALTER TABLE TBL_CMSEA11DATA_LOG ADD TYPE2 VARCHAR2(8);
UPDATE TBL_CMSEA11DATA_LOG SET TYPE2 = TYPE2_TMP;
ALTER TABLE TBL_CMSEA11DATA_LOG DROP COLUMN TYPE2_TMP;
COMMIT;

ALTER TABLE TBL_CMSEA11DATA_LOG ADD TYPE3_TMP VARCHAR2(8);
UPDATE TBL_CMSEA11DATA_LOG SET TYPE3_TMP = '0' || TYPE3;
ALTER TABLE TBL_CMSEA11DATA_LOG DROP COLUMN TYPE3;
ALTER TABLE TBL_CMSEA11DATA_LOG ADD TYPE3 VARCHAR2(8);
UPDATE TBL_CMSEA11DATA_LOG SET TYPE3 = TYPE3_TMP;
ALTER TABLE TBL_CMSEA11DATA_LOG DROP COLUMN TYPE3_TMP;
COMMIT;